### Exercise 1: Convert a list and tuple into arrays

In [1]:
import numpy as np

lst = [1,2,3,4,5,6,7,8]
arr = np.asarray(lst) 
print("List to array: ", arr)

tup = ([8,4,6], [1,2,3])
arr_t = np.asarray(tup)
print("Tuple to array: ",arr_t)


List to array:  [1 2 3 4 5 6 7 8]
Tuple to array:  [[8 4 6]
 [1 2 3]]


### Exercise 2: Convert the values of Centigrade degrees into Fahrenheit degrees

In [2]:
import numpy as np
Far = [ 0.,12.,45.21,34.,99.91]
arr_F = np.array(Far)
print("Values in Fahrenheit degrees:")
print(arr_F)
print("Values in  Centigrade degrees:") 
print(5*arr_F/9 - 17.77777777777778)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


### Exercise 3: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [3]:
n = np.array([1,20,33], dtype=np.float64)
print("Size of the array: ", n.size)
print("Length of one array element in bytes: ", n.itemsize)
print("Total bytes consumed by the elements of the array: ", n.nbytes)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


### Get the unique elements of an array

In [4]:
org_arr = np.array([10,10,20,20,30,30])
print("Original array: ",org_arr)
print("Unique elements of the above array:", np.unique(org_arr))

arr = np.array([[1, 1], [2, 3]])
print("Original array: ",arr)
print("Unique elements of the above array:")
print(np.unique(arr))

Original array:  [10 10 20 20 30 30]
Unique elements of the above array: [10 20 30]
Original array:  [[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


 ## Change the dimension of an array

In [11]:
arr = np.arange(1,10)
print("Original array: ",arr)
print("Change array shape to (3, 3):", arr.reshape(3,3))

Original array:  [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3): [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Exercise 6: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [12]:
np.linspace(2.5,6.5,30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

### Exercise 7: Convert 1-D arrays as columns into a 2-D array

In [15]:
arr1 = np.array([10,20,30])
print("Array1:", arr1)
arr2 = np.array([40,50,60])
print("Array2:", arr2)
arr = np.column_stack((arr1, arr2))
print("Converted Array:", arr)

Array1: [10 20 30]
Array2: [40 50 60]
Converted Array: [[10 40]
 [20 50]
 [30 60]]


### Exercise 8: Create a 5x5 matrix with row values ranging from 0 to 4

In [16]:
import numpy as np
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)


Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### Exercise 9: Sum of all the multiples of 3 or 5 below 100

In [17]:
x = np.arange(1, 100)
# find  multiple of 3 or 5
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:1000])
# print sum the numbers
print(n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


### Exercise 10: Combine a one and a two dimensional array together and display their elements

In [18]:
import numpy as np
x = np.arange(4)
print("One dimensional array:")
print(x)
y = np.arange(8).reshape(2,4)
print("Two dimensional array:")
print(y)
for a, b in np.nditer([x,y]):
    print("%d:%d" % (a,b),)

One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


### Exercise 11: Write a NumPy program to replace all elements of NumPy array that are greater than specified array

In [19]:
import numpy as np
x = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:")
print(x)
print("Replace all elements of the said array with .5 which are greater than .5")
x[x > .5] = .5
print(x)


Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


### Exercise 12: Add a new row to an empty numpy array

In [1]:
import numpy as np    
arr = np.empty((0,3), int)
print("Empty array:")
print(arr)
arr = np.append(arr, np.array([[10,20,30]]), axis=0)
arr = np.append(arr, np.array([[40,50,60]]), axis=0)
print("After adding two new arrays:")
print(arr)

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


### Write a NumPy program to join a sequence of arrays along a new axis

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3, 4])
print("Original arrays:")
print(arr1)
print(arr2)
print("Sequence of arrays along a new axis:")
print(np.stack((arr1, arr2)))

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[2], [3], [4]])
print("Original arrays:")
print(arr1)
print("\n",arr2) 

print("Sequence of arrays along a new axis:")
print(np.vstack((arr1, arr2)))

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]
Original arrays:
[[1]
 [2]
 [3]]

 [[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
